config/routes.rb
Who2vote::Application.routes.draw do
  mount RailsAdmin::Engine => '/manage', :as => 'rails_admin'
  devise_for :users

  get "filter" => "home#filter"
  root to: "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :access, :rails_admin
    can :dashboard
    can :manage, :all
    cannot :manage, User unless user.email == "rystraum@gmail.com"
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/politician.rb
class Politician < ActiveRecord::Base
  has_many :stances
  has_many :issues, through: :stances
  attr_accessible :description, :image_url, :name
  default_scope includes(:stances, :issues)
  
  class << self
    def get_by_stance(issues)
      politicians = []
      issues.each do |issue|
        issue.each_pair do |issue_id, stances|
          stances.each do |stance|
            stancev = case stance
                      when "pro"
                        1
                      when "anti"
                        -1
                      else
                        0
                      end
            
            politicians << Stance.where(issue_id: issue_id, stance: stancev).to_a
          end
        end
      end
      politicians.flatten.collect(&:politician).uniq
    end
  end
end

app/models/stance.rb
class Stance < ActiveRecord::Base
  belongs_to :politician
  belongs_to :issue
  
  attr_accessible :stance, :politician_id, :issue_id
  
  delegate :name, to: :politician, prefix: true
  delegate :name, to: :issue, prefix: true

  def pro?
    stance > 0
  end
  def anti?
    stance < 0
  end
  def neutral?
    stance == 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end
  before_filter :get_all_issues

  def get_all_issues
    @issues = Issue.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @politicians = Politician.all
  end

  def filter
    @politicians = Politician.get_by_stance(get_issues_and_stances) rescue Politician.all
    render "index"
  end

  def get_issues_and_stances
    issues = []
    params[:issues].each_pair do |issue_id, stances|
      stance_list = []
      stances.each_key do |key|
        stance_list << key
        instance_variable_set("@#{key}_#{issue_id}", true)
      end
      issues << { issue_id => stance_list }
    end
    issues
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash
   flash_messages = []
   flash.each do |type, message|
     type = :success if type == :notice
     type = :error   if type == :alert
     text = content_tag(:div, link_to("x", "#", :class => "close", "data-dismiss" => "alert") + message.html_safe, :class => "alert fade in alert-#{type}")
     flash_messages << text if message
   end
   flash_messages.join("\n").html_safe
 end
end

app/views/application/_politician_thumbnails.html.haml
- politicians.each_slice(3) do |pols|
  %ul.thumbnails= render pols

app/views/application/_sidebar.html.haml
.well
  %h4 Sort by issue:
  = form_tag filter_path, method: :get do
    - for issue in @issues
      %h6= issue.name
      %label.checkbox
        = check_box_tag "issues[#{issue.id}][pro]", 1, instance_variable_get("@pro_#{issue.id}")
        Pro
      %label.checkbox
        = check_box_tag "issues[#{issue.id}][anti]", 1, instance_variable_get("@anti_#{issue.id}")
        Anti
      %label.checkbox
        = check_box_tag "issues[#{issue.id}][neutral]", 1, instance_variable_get("@neutral_#{issue.id}")
        Neutral
    
    = submit_tag "Filter", class: "btn btn-primary"

app/views/home/index.html.haml
.row-fluid
  = render "politician_thumbnails", politicians: @politicians

app/views/layouts/application.html.haml
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %title Who to vote?
      %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
        %meta{:content => "", :name => "description"}
          %meta{:content => "", :name => "author"}
            / Le styles
            = stylesheet_link_tag    "application", :media => "all"
            = javascript_include_tag "application"
            = csrf_meta_tags
            :css
              body {
                padding-top: 60px;
                padding-bottom: 40px;
              }
              .sidebar-nav {
                padding: 9px 0;
              }
                / HTML5 shim, for IE6-8 support of HTML5 elements
            /[if lt IE 9]
              <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
            / Fav and touch icons
            / %link{:href => "../assets/ico/favicon.ico", :rel => "shortcut icon"}
            / %link{:href => "../assets/ico/apple-touch-icon-144-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "144x144"}
            / %link{:href => "../assets/ico/apple-touch-icon-114-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "114x114"}
            / %link{:href => "../assets/ico/apple-touch-icon-72-precomposed.png", :rel => "apple-touch-icon-precomposed", :sizes => "72x72"}
            / %link{:href => "../assets/ico/apple-touch-icon-57-precomposed.png", :rel => "apple-touch-icon-precomposed"}
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"} Forms
          .nav-collapse.collapse
            %ul.nav
              %li= link_to "Home", root_path
              %li= link_to "Manage", rails_admin_path
    .container-fluid
      .row-fluid
        .span9
          = bootstrap_flash
          = yield
        .span3
          = render "sidebar"
    %hr
      %footer
        %p &copy;

app/views/politicians/_politician.html.haml
%li.span4.politician
  .thumbnail= image_tag politician.image_url
  .stances= render politician.stances
  %h4= politician.name
  %p= politician.description

app/views/stances/_stance.html.haml
- if stance.pro?
  %button.btn.btn-success.pro
    %i.icon-thumbs-up
    #{stance.issue_name}

- elsif stance.anti?
  %button.btn.btn-danger.anti
    %i.icon-thumbs-down.icon-white
    #{stance.issue_name}

- else
  %button.btn #{stance.issue_name}